[package]
name = "wbqrgen"
version = "0.1.0"
edition = "2021"
author = "Gurm4n"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = ["derive"] }
qrcode-generator = "4.1.8"
